### ISSUE TITLE
CONFIG_FILE

### ISSUE THREAD

**Issue by Shixiaomeng7** [Xiangxu-0103/FRNet#1]
Sorry, I can't seem to find a config yaml file for the corresponding model.

**Comment by Xiangxu-0103** [comment]
Hi, @Shixiaomeng7 , thanks for your interest in this work. The config files are under `configs/frnet` directory with `python` style.

**Comment by Shixiaomeng7** [comment]
Thank you very much for your answer!



At 2023-12-13 21:35:02, "Xiang Xu" ***@***.***> wrote:

Hi, @Shixiaomeng7 , thanks for your interest in this work. The config files are under configs/frnet directory with python style.
