### ISSUE TITLE
About infer

### ISSUE THREAD

**Issue by Wansit99** [Xiangxu-0103/FRNet#10]
May I ask how I can use FRNet for inference to obtain visualized results? Currently, I can get the mIoU, but I also want to obtain the corresponding point cloud inference results. Thank you!

**Comment by Xiangxu-0103** [comment]
For visualization, you may refer to [mmdet3d](https://github.com/open-mmlab/mmdetection3d) for details.

**Comment by Wansit99** [comment]
> For visualization, you may refer to [mmdet3d](https://github.com/open-mmlab/mmdetection3d) for details.

Thanks！

**Comment by Lizhijian-123** [comment]
> May I ask how I can use FRNet for inference to obtain visualized results? Currently, I can get the mIoU, but I also want to obtain the corresponding point cloud inference results. Thank you!

May I ask how many val miou and test miou you had in semanticKITTI before using TTA? How much after tta? I saw that your test miou in semanticKITTI was only about 68.7 before, and it reached 73.3 in the paper. Have you reproduced this result? What is your current test miou? Do you have any tricks?Thanks
