### ISSUE TITLE
About how to test

### ISSUE THREAD

**Issue by xiaosa269** [Xiangxu-0103/FRNet#15]
Hello,

I'm a beginner and it's my first time debugging code. When running the test code python test.py ${CONFIG_FILE} ${CHECKPOINT_FILE}, what file path should be provided for ${CONFIG_FILE}? Do I need to generate it myself? If so, how can I generate it? And for ${CHECKPOINT_FILE}, is it correct to input the path of the pre-trained checkpoints you provided? Thank you very much for your help.

**Comment by ymlzOvO** [comment]
CONFIG_FILE is like `configs/frnet/frnet-semantickitti_seg.py`

**Comment by xiaosa269** [comment]
Thank you！
