### ISSUE TITLE
freeze model

### ISSUE THREAD

**Issue by Wansit99** [Xiangxu-0103/FRNet#18]
Hello, could you please advise on how to freeze network parameters? For example, if I only want to train `frnet_head`.

**Comment by Xiangxu-0103** [comment]
You can freeze some modules [here](https://github.com/Xiangxu-0103/FRNet/blob/master/frnet/models/segmentors/frnet.py#L57) by adding the following code (taking backbone as an example):

```python
self.backbone.eval()
for param in self.backbone.parameters():
    param.requires_grad = False
```

Hope the reply can help you.

**Comment by Wansit99** [comment]
> You can freeze some modules [here](https://github.com/Xiangxu-0103/FRNet/blob/master/frnet/models/segmentors/frnet.py#L57) by adding the following code (taking backbone as an example):
> 
> ```python
> self.backbone.eval()
> for param in self.backbone.parameters():
>     param.requires_grad = False
> ```
> 
> Hope the reply can help you.

Thanks！
