### ISSUE TITLE
param and fps

### ISSUE THREAD

**Issue by wp664** [Xiangxu-0103/FRNet#19]
Hello, could you please tell me how to obtain param and fps?

**Comment by Xiangxu-0103** [comment]
Hi @wp664, for FPS, you can follow this [script](https://github.com/open-mmlab/mmdetection3d/blob/main/tools/analysis_tools/benchmark.py) provided in `mmdet3d`. While for param, you can refer to the [parameter_count_table](https://github.com/open-mmlab/mmengine/blob/main/mmengine/analysis/complexity_analysis.py#L295) implemented in `mmengine`.

**Comment by wp664** [comment]
@Xiangxu-0103, Thanks.

**Comment by wp664** [comment]
I ran the following command and got around 18 fps on the 3090, which is quite different from the 29.1 mentioned in the paper. Do I need to do anything else? Thank you for your help.
python mmdetection3d/tools/analysis_tools/benchmark.py configs/frnet/frnet-semantickitti_seg.py frnet-semantickitti_seg.pth

**Comment by Xiangxu-0103** [comment]
Hi, the FPS is calculated under `fp16` mode.
