### ISSUE TITLE
run on customized dataset

### ISSUE THREAD

**Issue by ymlzOvO** [Xiangxu-0103/FRNet#20]
Hi! I found it performs wonderfully in semantic-kitti! But now, I have some data collected by myself, similar street scene like kitti. If I want to run your model on it directly, need I just format my data as kitti and then run as semantic-kitti test dataset? Or I need to do something more? Thank you!

**Comment by Xiangxu-0103** [comment]
@ymlzOvO, thanks for your interest in our work.  For a new dataset, you may need to follow the following steps:

1. Create `pkl` files for `train` and `val` set. The format of the `pkl` file can be referred to `create_semantickitti.py`.
2. Custom your own dataset like `SemanticKITTIDataset` (already implemented in mmdet3d), or `NuScenesSegDataset` (implemented in this repo).
3. Prepare the config file.

Feel free to let me know if the above resolves your question.

**Comment by ymlzOvO** [comment]
> @ymlzOvO, thanks for your interest in our work. For a new dataset, you may need to follow the following steps:
> 
> 1. Create `pkl` files for `train` and `val` set. The format of the `pkl` file can be referred to `create_semantickitti.py`.
> 2. Custom your own dataset like `SemanticKITTIDataset` (already implemented in mmdet3d), or `NuScenesSegDataset` (implemented in this repo).
> 3. Prepare the config file.
> 
> Feel free to let me know if the above resolves your question.

Thank you for your reply! I've saved my results of custom dataset though it seems to be uncorrect after visualization. Perhaps there's something wrong with my dataset. May I ask if your algorithm utilizes the `intensity` of kitti? For it's `xyzi`, I do not have `intensity` and use randomly generated value.

**Comment by Wansit99** [comment]
> > @ymlzOvO, thanks for your interest in our work. For a new dataset, you may need to follow the following steps:
> > 
> > 1. Create `pkl` files for `train` and `val` set. The format of the `pkl` file can be referred to `create_semantickitti.py`.
> > 2. Custom your own dataset like `SemanticKITTIDataset` (already implemented in mmdet3d), or `NuScenesSegDataset` (implemented in this repo).
> > 3. Prepare the config file.
> > 
> > Feel free to let me know if the above resolves your question.
> 
> Thank you for your reply! I've saved my results of custom dataset though it seems to be uncorrect after visualization. Perhaps there's something wrong with my dataset. May I ask if your algorithm utilizes the `intensity` of kitti? For it's `xyzi`, I do not have `intensity` and use randomly generated value.

FRNet use intensity in KITTI

**Comment by Xiangxu-0103** [comment]
Hi @ymlzOvO , we use the intensity information in our FRNet. Also, if your dataset do not have `intensity`, we suggest to use only `xyz` instead of randomly generated value and we believe it also works.

**Comment by ymlzOvO** [comment]
> Hi @ymlzOvO , we use the intensity information in our FRNet. Also, if your dataset do not have `intensity`, we suggest to use only `xyz` instead of randomly generated value and we believe it also works.

Thank you! For using `xyz` only, I think what I need to do is to modify
```python
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
```
in `test_dataloader` and `test_pipeline`, letting `load_dim` and `use_dim` from `4` to `3`, is that right?

**Comment by Xiangxu-0103** [comment]
`load_dim` and `use_dim` should be set according to the dataset. `load_dim` means the dimensional your dataset owns, and `use_dims` means which dimension you require (`use_dim=4` means we use `[0, 1, 2, 3]` dims here).

**Comment by ymlzOvO** [comment]
> `load_dim` and `use_dim` should be set according to the dataset. `load_dim` means the dimensional your dataset owns, and `use_dims` means which dimension you require (`use_dim=4` means we use `[0, 1, 2, 3]` dims here).

That's to say, if my dataset contains `xyz` only, I should use
```python
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=3,
        type='LoadPointsFromFile',
        use_dim=3),
```
Yeah? I'll have a try. Thanks!

**Comment by ymlzOvO** [comment]
> `load_dim` and `use_dim` should be set according to the dataset. `load_dim` means the dimensional your dataset owns, and `use_dims` means which dimension you require (`use_dim=4` means we use `[0, 1, 2, 3]` dims here).

Oh, to run on `xyz`, there're extra changes which should be made. Besides `load_dim` and `use_dim`, `in_channel` should also be set as `3`. Moreover, I have to modify your source codes in `frnet/datasets/transforms/transforms_3d.py` to fit the changes of dimension for the original codes consider only `dim=4`.

The results (`xyz` only) are more reasonable than before (with wrong `intensity`)!
