### ISSUE TITLE
About update

### ISSUE THREAD

**Issue by Wansit99** [Xiangxu-0103/FRNet#21]
I'm so glad you've updated your nice work. Could you please provide details on what specific updates have been made to enhance stability?Thanks!

**Comment by Wansit99** [comment]
And when I update this files, I meet some problems

  File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/segmentors/frnet.py", line 83, in extract_feat
    voxel_dict = self.voxel_encoder(voxel_dict)
  File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/voxel_encoders/frustum_encoder.py", line 106, in forward
    voxel_feats = torch_scatter.scatter_max(
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch_scatter/scatter.py", line 79, in scatter_max
        out: Optional[torch.Tensor] = None,
        dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: "scatter" not implemented for 'Half'

**Comment by Wansit99** [comment]
[my torch_scatter version is 2.0.6

> And when I update this files, I meet some problems
> 
> File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/segmentors/frnet.py", line 83, in extract_feat voxel_dict = self.voxel_encoder(voxel_dict) File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/voxel_encoders/frustum_encoder.py", line 106, in forward voxel_feats = torch_scatter.scatter_max( RuntimeError: The following operation failed in the TorchScript interpreter. Traceback of TorchScript (most recent call last): File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch_scatter/scatter.py", line 79, in scatter_max out: Optional[torch.Tensor] = None, dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]: return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE RuntimeError: "scatter" not implemented for 'Half'

and my torch_scatter version is 2.0.6

**Comment by Wansit99** [comment]
> And when I update this files, I meet some problems
> 
> File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/segmentors/frnet.py", line 83, in extract_feat voxel_dict = self.voxel_encoder(voxel_dict) File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl result = self.forward(*input, **kwargs) File "/opt/data/private/whu_wsy/seg/FRNet-master-init/frnet/models/voxel_encoders/frustum_encoder.py", line 106, in forward voxel_feats = torch_scatter.scatter_max( RuntimeError: The following operation failed in the TorchScript interpreter. Traceback of TorchScript (most recent call last): File "/opt/conda/envs/frnet/lib/python3.8/site-packages/torch_scatter/scatter.py", line 79, in scatter_max out: Optional[torch.Tensor] = None, dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]: return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE RuntimeError: "scatter" not implemented for 'Half'
> 
> my torch_scatter version is 2.0.6

It works well in 2.0.8

**Comment by Xiangxu-0103** [comment]
Thanks for your continuous attention to our work. In the updated version, we tried to use `iter-based` training instead of `epoch-based` training and use `mixed precision` (successful in `SemanticKITTI` while a little problem in `nuScenes`). All the models are trained with 4 GPUs and batch size is set to `4` for each GPU. If your configuration differs from ours, you may need to adjust the `max_iters` in the config.

**Comment by Wansit99** [comment]
Thank you for your prompt response. After using the new config, I noticed a significant decrease in training speed, almost 1.5 times slower. Even after disabling mixed precision through onecycle-50k.py, there's still around a 1.3 times decrease in speed. What could be the reason for this?

**Comment by Wansit99** [comment]
> Thanks for your continuous attention to our work. In the updated version, we tried to use `iter-based` training instead of `epoch-based` training and use `mixed precision` (successful in `SemanticKITTI` while a little problem in `nuScenes`). All the models are trained with 4 GPUs and batch size is set to `4` for each GPU. If your configuration differs from ours, you may need to adjust the `max_iters` in the config.

Could you clarify what nuScenes is? I've been experimenting with KITTI so far, but I'll need to work with nuScenes soon. Thank you!

**Comment by Xiangxu-0103** [comment]
Here, we provide the [training log](https://github.com/Xiangxu-0103/FRNet/files/15136880/20240316_144229.log), which is trained with `4xb4`.

For nuScenes, you may refer to [website](https://www.nuscenes.org/) for downloading and prepare the dataset as mentioned in the document.

**Comment by Wansit99** [comment]
> Here, we provide the [training log](https://github.com/Xiangxu-0103/FRNet/files/15136880/20240316_144229.log), which is trained with `4xb4`.
> 
> For nuScenes, you may refer to [website](https://www.nuscenes.org/) for downloading and prepare the dataset as mentioned in the document.

Thanks! But I have a question about the val batch_size, why it needs to be set to 1?

**Comment by Wansit99** [comment]
> Here, we provide the [training log](https://github.com/Xiangxu-0103/FRNet/files/15136880/20240316_144229.log), which is trained with `4xb4`.
> 
> For nuScenes, you may refer to [website](https://www.nuscenes.org/) for downloading and prepare the dataset as mentioned in the document.

And I find the version in the INSTALL.md is not same as the log,could you update them? Thanks!

**Comment by Wansit99** [comment]
> Here, we provide the [training log](https://github.com/Xiangxu-0103/FRNet/files/15136880/20240316_144229.log), which is trained with `4xb4`.
> 
> For nuScenes, you may refer to [website](https://www.nuscenes.org/) for downloading and prepare the dataset as mentioned in the document.

It works well when I update torch from 1.8.1 to 1.11.0
and this is the conda environment by conda list:

_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  22.1.0                   pypi_0    pypi
aiosqlite                 0.20.0                   pypi_0    pypi
aliyun-python-sdk-core    2.15.1                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
anyio                     4.3.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
black                     24.4.2                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0  
cachetools                5.3.3                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.8.1                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
fire                      0.6.0                    pypi_0    pypi
flake8                    7.0.0                    pypi_0    pypi
fonttools                 4.51.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
google-auth               2.29.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.62.2                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
importlib-metadata        7.1.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.29.4                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.2                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.0                    pypi_0    pypi
json5                     0.9.25                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            7.4.9                    pypi_0    pypi
jupyter-core              5.7.2                    pypi_0    pypi
jupyter-events            0.10.0                   pypi_0    pypi
jupyter-packaging         0.12.3                   pypi_0    pypi
jupyter-server            2.14.0                   pypi_0    pypi
jupyter-server-fileid     0.9.2                    pypi_0    pypi
jupyter-server-terminals  0.5.3                    pypi_0    pypi
jupyter-server-ydoc       0.8.0                    pypi_0    pypi
jupyter-ydoc              0.2.5                    pypi_0    pypi
jupyterlab                3.6.7                    pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.27.1                   pypi_0    pypi
jupyterlab-widgets        3.0.10                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.41.1                   pypi_0    pypi
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mmcv                      2.1.0                    pypi_0    pypi
mmdet                     3.2.0                    pypi_0    pypi
mmdet3d                   1.4.0                    pypi_0    pypi
mmengine                  0.10.4                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.10.0                   pypi_0    pypi
nbconvert                 7.16.3                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
notebook                  6.5.6                    pypi_0    pypi
notebook-shim             0.2.4                    pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nuscenes-devkit           1.1.11                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
open3d-python             0.3.0.0                  pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openmim                   0.3.9                    pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
openxlab                  0.0.38                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
overrides                 7.7.0                    pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.2.1                    pypi_0    pypi
plotly                    5.21.0                   pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
plyfile                   1.0.3                    pypi_0    pypi
prometheus-client         0.20.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
protobuf                  5.26.1                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0                    pypi_0    pypi
pycocotools               2.0.7                    pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pytest                    8.1.2                    pypi_0    pypi
python                    3.8.10               h12debd9_8  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.21.0                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.3                    pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   1.8.5.post1              pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminado                 0.18.1                   pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
threadpoolctl             3.4.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tinycss2                  1.3.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.12.4                   pypi_0    pypi
torch                     1.11.0+cu113             pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.65.2                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
trimesh                   4.3.1                    pypi_0    pypi
types-python-dateutil     2.9.0.20240316           pypi_0    pypi
typing-extensions         4.11.0                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.8.0                    pypi_0    pypi
werkzeug                  3.0.2                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0  
widgetsnbextension        4.0.10                   pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
y-py                      0.6.2                    pypi_0    pypi
yapf                      0.40.2                   pypi_0    pypi
ypy-websocket             0.8.4                    pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by Wansit99** [comment]
Here is the mm version suitable for torch 1.11.0
'mmdet3d==1.4.0'

**Comment by Xiangxu-0103** [comment]
I think the latest version is also compatible to our repo.
