### ISSUE TITLE
About export prediction results

### ISSUE THREAD

**Issue by Wansit99** [Xiangxu-0103/FRNet#22]
Could you please guide me on how to export prediction results using code? I want to submit them to the KITTI leaderboard.Thanks!

**Comment by Xiangxu-0103** [comment]
Sorry for late reply. I suggest you customize a new `Evaluator` instead of `SegMetric`, in which you can define your own operation, such as remapping the predicted label to the original label and saving the label. It is easy to debug from my perspective.

**Comment by Wansit99** [comment]
> Sorry for late reply. I suggest you customize a new `Evaluator` instead of `SegMetric`, in which you can define your own operation, such as remapping the predicted label to the original label and saving the label. It is easy to debug from my perspective.

Thanks!
