### ISSUE TITLE
How to visualize

### ISSUE THREAD

**Issue by xiaosa269** [Xiangxu-0103/FRNet#25]
Hello, thank you very much for your work. I would like to visualize the test results of the semanticKITTI dataset and record the FPS. How should I proceed? Thank you very much for your help。

**Comment by Xiangxu-0103** [comment]
Sorry for late reply. For visualization, you may refer to #14 for details. For fps evaluation, you may refer to #19.

**Comment by xiaosa269** [comment]
thanks
