### ISSUE TITLE
About FPS

### ISSUE THREAD

**Issue by Wansit99** [Xiangxu-0103/FRNet#26]
Thank you for your patience with each response.And How can I obtain the FPS mentioned in the text? Do I need additional scripts for that?

**Comment by ldkong1205** [comment]
Hi @Wansit99, for the calculation of FPS, please refer to https://github.com/Xiangxu-0103/FRNet/issues/19.

**Comment by Wansit99** [comment]
> Hi @Wansit99, for the calculation of FPS, please refer to #19.
Thanks!
