### ISSUE TITLE
add some points, original point's label will be change

### ISSUE THREAD

**Issue by xunkaixin** [Xiangxu-0103/FRNet#31]
Original point cloud p0, p1, p2, p3, ... pn,  Obtain inference results L0, L1, L2, L3,... Ln
Add some points (from original) to the original point cloud to form a new point cloud p0, p1, p2, p3, ... pn, p2, p3,  Will cause a change in the inference category of the original point cloud

Is it my mistake or is it that the result of  algorithm  is like this？

**Comment by Xiangxu-0103** [comment]
I am sorry that I cannot understand what you mean. Can you provide your questions more clearly?

**Comment by xunkaixin** [comment]
Assuming there are 1000 points in the original point cloud, infer and obtain the category of the points; Randomly select 10 points from the original point cloud and add them to the end of the original point cloud to form 1010 points, and then perform inference. The inference result will change the inference result of 1000 points; In other words, 10 additional points changed the category of 1000 points
