### ISSUE TITLE
About your paper.

### ISSUE THREAD

**Issue by hyalvin** [Xiangxu-0103/FRNet#5]
![image](https://github.com/Xiangxu-0103/FRNet/assets/81557866/ac585157-6c67-46a8-9a89-30858ea87998)
Here, if following the representation in your code as:
![image](https://github.com/Xiangxu-0103/FRNet/assets/81557866/8321d97d-3524-416f-9f13-b43ba7d6185e)
should `f_up` be `|f_down|`?

**Comment by Xiangxu-0103** [comment]
Sorry for the late reply. Thanks for your pointing out the problem. It seems an error in the paper, which is also presented in RangeNet++. We will modify the equation in the next version.

**Comment by hyalvin** [comment]
> Sorry for the late reply. Thanks for your pointing out the problem. It seems an error in the paper, which is also presented in RangeNet++. We will modify the equation in the next version.

One more potential error,
![image](https://github.com/Xiangxu-0103/FRNet/assets/81557866/b11ebcb2-5126-429f-97fd-9baeef614454)
Here, I guess f_ik means the feature of the k-th point in the i-th frustum region.

**Comment by Xiangxu-0103** [comment]
@hyalvin Thanks again for your correction.
